# This workflow builds a Clojure project using Leiningen
# For more information see: https://github.com/technomancy/leiningen

name: Clojure CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Clojure
        run: |
          echo "Installing Clojure and Leiningen..."
          curl -O https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
          chmod +x lein
          sudo mv lein /usr/local/bin/lein
          lein self-install
          echo "Clojure and Leiningen installed successfully."

      - name: Install Dependencies
        run: |
          echo "Installing project dependencies..."
          lein deps

      - name: Run Tests
        run: |
          echo "Running tests..."
          lein test
